title: Ibrahim Giwa
logo: "https://github.com/Giwa-ibrahim/Portfolio/blob/main/My%20Professional%20Picture.jpeg" # your photo (or logo) here
description: Research Assistant and Machine learning Intern
theme: jekyll-theme-slate
